#include "window_win32_plugin_key_converter.h"

#include <Windows.h>

#include <window_interface.h>

WindowEventKey win32_key_to_window_event_key(uintptr_t wparam)
{
    switch (wparam)
    {
    case 'A':
        return WINDOW_EVENT_KEY_A;
    case 'B':
        return WINDOW_EVENT_KEY_B;
    case 'C':
        return WINDOW_EVENT_KEY_C;
    case 'D':
        return WINDOW_EVENT_KEY_D;
    case 'E':
        return WINDOW_EVENT_KEY_E;
    case 'F':
        return WINDOW_EVENT_KEY_F;
    case 'G':
        return WINDOW_EVENT_KEY_G;
    case 'H':
        return WINDOW_EVENT_KEY_H;
    case 'I':
        return WINDOW_EVENT_KEY_I;
    case 'J':
        return WINDOW_EVENT_KEY_J;
    case 'K':
        return WINDOW_EVENT_KEY_K;
    case 'L':
        return WINDOW_EVENT_KEY_L;
    case 'M':
        return WINDOW_EVENT_KEY_M;
    case 'N':
        return WINDOW_EVENT_KEY_N;
    case 'O':
        return WINDOW_EVENT_KEY_O;
    case 'P':
        return WINDOW_EVENT_KEY_P;
    case 'Q':
        return WINDOW_EVENT_KEY_Q;
    case 'R':
        return WINDOW_EVENT_KEY_R;
    case 'S':
        return WINDOW_EVENT_KEY_S;
    case 'T':
        return WINDOW_EVENT_KEY_T;
    case 'U':
        return WINDOW_EVENT_KEY_U;
    case 'V':
        return WINDOW_EVENT_KEY_V;
    case 'W':
        return WINDOW_EVENT_KEY_W;
    case 'X':
        return WINDOW_EVENT_KEY_X;
    case 'Y':
        return WINDOW_EVENT_KEY_Y;
    case 'Z':
        return WINDOW_EVENT_KEY_Z;

    case '0':
        return WINDOW_EVENT_KEY_0;
    case '1':
        return WINDOW_EVENT_KEY_1;
    case '2':
        return WINDOW_EVENT_KEY_2;
    case '3':
        return WINDOW_EVENT_KEY_3;
    case '4':
        return WINDOW_EVENT_KEY_4;
    case '5':
        return WINDOW_EVENT_KEY_5;
    case '6':
        return WINDOW_EVENT_KEY_6;
    case '7':
        return WINDOW_EVENT_KEY_7;
    case '8':
        return WINDOW_EVENT_KEY_8;
    case '9':
        return WINDOW_EVENT_KEY_9;

    case VK_F1:
        return WINDOW_EVENT_KEY_F1;
    case VK_F2:
        return WINDOW_EVENT_KEY_F2;
    case VK_F3:
        return WINDOW_EVENT_KEY_F3;
    case VK_F4:
        return WINDOW_EVENT_KEY_F4;
    case VK_F5:
        return WINDOW_EVENT_KEY_F5;
    case VK_F6:
        return WINDOW_EVENT_KEY_F6;
    case VK_F7:
        return WINDOW_EVENT_KEY_F7;
    case VK_F8:
        return WINDOW_EVENT_KEY_F8;
    case VK_F9:
        return WINDOW_EVENT_KEY_F9;
    case VK_F10:
        return WINDOW_EVENT_KEY_F10;
    case VK_F11:
        return WINDOW_EVENT_KEY_F11;
    case VK_F12:
        return WINDOW_EVENT_KEY_F12;

    case VK_SPACE:
        return WINDOW_EVENT_KEY_SPACE;
    case VK_OEM_7:
        return WINDOW_EVENT_KEY_APOSTROPHE;
    case VK_OEM_COMMA:
        return WINDOW_EVENT_KEY_COMMA;
    case VK_OEM_MINUS:
        return WINDOW_EVENT_KEY_MINUS;
    case VK_OEM_PERIOD:
        return WINDOW_EVENT_KEY_PERIOD;
    case VK_OEM_2:
        return WINDOW_EVENT_KEY_SLASH;
    case VK_OEM_1:
        return WINDOW_EVENT_KEY_SEMICOLON;
        // In windows the EQUAL key is named after the shift +
    case VK_OEM_PLUS:
        return WINDOW_EVENT_KEY_EQUAL;
    case VK_OEM_4:
        return WINDOW_EVENT_KEY_LEFT_BRACKET;
    case VK_OEM_5:
        return WINDOW_EVENT_KEY_BACKSLASH;
    case VK_OEM_6:
        return WINDOW_EVENT_KEY_RIGHT_BRACKET;
    case VK_OEM_3:
        return WINDOW_EVENT_KEY_GRAVE_ACCENT;

    case VK_ESCAPE:
        return WINDOW_EVENT_KEY_ESCAPE;
    case VK_RETURN:
        return WINDOW_EVENT_KEY_ENTER;
    case VK_TAB:
        return WINDOW_EVENT_KEY_TAB;
    case VK_BACK:
        return WINDOW_EVENT_KEY_BACKSPACE;
    case VK_INSERT:
        return WINDOW_EVENT_KEY_INSERT;
    case VK_DELETE:
        return WINDOW_EVENT_KEY_DELETE;
    case VK_RIGHT:
        return WINDOW_EVENT_KEY_RIGHT;
    case VK_LEFT:
        return WINDOW_EVENT_KEY_LEFT;
    case VK_DOWN:
        return WINDOW_EVENT_KEY_DOWN;
    case VK_UP:
        return WINDOW_EVENT_KEY_UP;
    case VK_PRIOR:
        return WINDOW_EVENT_KEY_PAGE_UP;
    case VK_NEXT:
        return WINDOW_EVENT_KEY_PAGE_DOWN;
    case VK_HOME:
        return WINDOW_EVENT_KEY_HOME;
    case VK_END:
        return WINDOW_EVENT_KEY_END;
    case VK_CAPITAL:
        return WINDOW_EVENT_KEY_CAPS_LOCK;
    case VK_SCROLL:
        return WINDOW_EVENT_KEY_SCROLL_LOCK;
    case VK_NUMLOCK:
        return WINDOW_EVENT_KEY_NUM_LOCK;
    case VK_SNAPSHOT:
        return WINDOW_EVENT_KEY_PRINT_SCREEN;
    case VK_PAUSE:
        return WINDOW_EVENT_KEY_PAUSE;

    case VK_SHIFT:
        return WINDOW_EVENT_KEY_LEFT_SHIFT;
    case VK_CONTROL:
        return WINDOW_EVENT_KEY_LEFT_CONTROL;
    case VK_MENU:
        return WINDOW_EVENT_KEY_LEFT_ALT;
    case VK_LWIN:
        return WINDOW_EVENT_KEY_LEFT_SUPER;
    case VK_RWIN:
        return WINDOW_EVENT_KEY_RIGHT_SUPER;
    case VK_APPS:
        return WINDOW_EVENT_KEY_MENU;

    case VK_NUMPAD0:
        return WINDOW_EVENT_KEY_NUMPAD_0;
    case VK_NUMPAD1:
        return WINDOW_EVENT_KEY_NUMPAD_1;
    case VK_NUMPAD2:
        return WINDOW_EVENT_KEY_NUMPAD_2;
    case VK_NUMPAD3:
        return WINDOW_EVENT_KEY_NUMPAD_3;
    case VK_NUMPAD4:
        return WINDOW_EVENT_KEY_NUMPAD_4;
    case VK_NUMPAD5:
        return WINDOW_EVENT_KEY_NUMPAD_5;
    case VK_NUMPAD6:
        return WINDOW_EVENT_KEY_NUMPAD_6;
    case VK_NUMPAD7:
        return WINDOW_EVENT_KEY_NUMPAD_7;
    case VK_NUMPAD8:
        return WINDOW_EVENT_KEY_NUMPAD_8;
    case VK_NUMPAD9:
        return WINDOW_EVENT_KEY_NUMPAD_9;
    case VK_DECIMAL:
        return WINDOW_EVENT_KEY_NUMPAD_DECIMAL;
    case VK_DIVIDE:
        return WINDOW_EVENT_KEY_NUMPAD_DIVIDE;
    case VK_MULTIPLY:
        return WINDOW_EVENT_KEY_NUMPAD_MULTIPLY;
    case VK_SUBTRACT:
        return WINDOW_EVENT_KEY_NUMPAD_SUBTRACT;
    case VK_ADD:
        return WINDOW_EVENT_KEY_NUMPAD_ADD;

    default:
        return 0;
    }
}