max_plugin_amount=64
memory_arena_size="100*KiB"

[requested_plugins]
# plugin_manager = {plugin_name = "default"}
# logger = {}
gui_application = { lifetime = "singleton" }



# { interface_name = "draw_2d" },
