max_plugin_amount = 64
memory_arena_size = "200*KiB"
# memory_arena_size = "256*KiB"

[requested_plugins]
# plugin_manager = {plugin_name = "default"}
logger = { lifetime = "singleton" }
gui_application = { lifetime = "singleton" }
allocator = { lifetime = "singleton" }


# { interface_name = "draw_2d" },
