plugin_manifests = [
    "C:/Users/Blue-WaveMathijsFran/Documents/GitHub/notepad-c/lib/plugin_manager/internal_plugins/environment_default",
    "C:/Users/Blue-WaveMathijsFran/Documents/GitHub/notepad-c/lib/plugin_manager/internal_plugins/logger_console",
    "C:/Users/Blue-WaveMathijsFran/Documents/GitHub/notepad-c/plugins/gui_application_default",
    "C:/Users/Blue-WaveMathijsFran/Documents/GitHub/notepad-c/plugins/window_win32",
    "C:/Users/Blue-WaveMathijsFran/Documents/GitHub/notepad-c/plugins/input_default",
    "C:/Users/Blue-WaveMathijsFran/Documents/GitHub/notepad-c/plugins/draw_default",
    "C:/Users/Blue-WaveMathijsFran/Documents/GitHub/notepad-c/plugins/draw_2d_default",
]

interfaces = [
    { interface_name = "environment", default = "default" },
    { interface_name = "logger", default = "console" },
    { interface_name = "window", default = [
        { target = "win32", plugin_name = "win32" },
    ] },
    { interface_name = "gui_application", default = "default" },
    { interface_name = "draw", default = "default" },
    { interface_name = "input", default = "default" },
    { interface_name = "draw_2d", default = "default" },
]
