plugin_manifests = [
    "${plugin_registry}/plugins/plugin_manager_default",
    "${plugin_registry}/plugins/environment_default",
    "${plugin_registry}/plugins/logger_console",
    "${plugin_registry}/plugins/gui_application_default",
    "${plugin_registry}/plugins/window_win32",
    "${plugin_registry}/plugins/input_default",
    "${plugin_registry}/plugins/draw_default",
    "${plugin_registry}/plugins/draw_2d_default",
    "${plugin_registry}/plugins/renderer_vulkan",
    "${plugin_registry}/plugins/time_win32",
    "${plugin_registry}/plugins/arena_allocator_default",
]

interfaces = [
    { interface_name = "plugin_manager", default = "default" },
    { interface_name = "environment", default = "default" },
    { interface_name = "logger", default = "console" },
    { interface_name = "window", default = [
        { target = "win32", plugin_name = "win32" },
    ] },
    { interface_name = "time", default = [
        { target = "win32", plugin_name = "win32" },
    ] },
    { interface_name = "gui_application", default = "default" },
    { interface_name = "draw", default = "default" },
    { interface_name = "input", default = "default" },
    { interface_name = "draw_2d", default = "default" },
    { interface_name = "renderer", default = "vulkan" },
    { interface_name = "arena_allocator", default="default"}
]

# TODO: Make this work like this
# [defaults]
# plugin_manager = "default"
# environment = "default"
# logger = "console"
# gui_application = "default"
# draw = "default"
# input = "default"
# draw_2d = "default"
# renderer = "vulkan"

# # Platform-specific overrides use a nested table
# [defaults.window]
# win32 = "win32"
# linux = "x11"
# wasm = "html5"
