#pragma once

#include <stdint.h>

#include <plugin_sdk/renderer/v1/renderer_types.h>

#include "renderer_vulkan_utils.h"

struct RendererContext;
struct RendererPipelineLayoutCreateInfo;
struct RendererGraphicsPipelineCreateInfo;
struct RendererComputePipelineCreateInfo;

int32_t renderer_vulkan_create_shader(struct RendererContext *context, const uint32_t *shader_code_u32, size_t shader_code_bytes_len, RendererShaderHandle *out_shader_module);
int32_t renderer_vulkan_destroy_shader(struct RendererContext *context, RendererShaderHandle shader_handle);

int32_t renderer_vulkan_create_pipeline_layout(struct RendererContext *context, const struct RendererPipelineLayoutCreateInfo *renderer_pipeline_layout_create_info, RendererPipelineLayoutHandle *out_pipeline_layout_handle);
int32_t renderer_vulkan_destroy_pipeline_layout(struct RendererContext *context, RendererPipelineLayoutHandle pipeline_handle);

int32_t renderer_vulkan_create_graphics_pipeline(struct RendererContext *context, const struct RendererGraphicsPipelineCreateInfo *renderer_pipeline_create_info, RendererGraphicsPipelineHandle *out_pipeline_handle);
int32_t renderer_vulkan_create_compute_pipeline(struct RendererContext *context, const struct RendererComputePipelineCreateInfo *renderer_pipeline_create_info, RendererComputePipelineHandle *out_pipeline_handle);
int32_t renderer_vulkan_destroy_graphics_pipeline(struct RendererContext *context, RendererGraphicsPipelineHandle pipeline_handle);
int32_t renderer_vulkan_destroy_compute_pipeline(struct RendererContext *context, RendererComputePipelineHandle pipeline_handle);