#pragma once
#include <stdint.h>

#include <plugin_sdk/renderer/v1/renderer_types.h>

#include "renderer_vulkan_utils.h"

typedef enum RendererAttachmentType
{
    RENDERER_ATTACHMENT_TYPE_COLOR,
    RENDERER_ATTACHMENT_TYPE_DEPTH,
} RendererAttachmentType;

RV_CREATE_HANDLE_DEFINITION(VkSemaphore);
RV_CREATE_HANDLE_DEFINITION(VkCommandBuffer);
RV_CREATE_HANDLE_DEFINITION(VkImage);
RV_CREATE_HANDLE_DEFINITION(VkBuffer);

struct VkImageSubresourceRange;
enum VkImageLayout;
struct VkSemaphoreSubmitInfo;
struct VkSubmitInfo2;
struct VkCommandBufferSubmitInfo;
struct VkSemaphoreSubmitInfo;
struct VkExtent2D;
struct VkExtent3D;
struct VkImageViewCreateInfo;
struct VkRenderingAttachmentInfo;
enum VkFormat;

typedef uint32_t VkImageAspectFlags;
typedef uint64_t VkPipelineStageFlags2;
struct VkExtent2D;
struct RV_VkExtent2D;

typedef uint32_t RendererShaderStageFlags;
typedef uint32_t VkShaderStageFlags;
typedef uint32_t RendererBufferUsageFlags;
typedef uint32_t VkBufferUsageFlags;
typedef uint32_t VkImageUsageFlags;
typedef uint32_t RendererImageUsageFlags;
typedef uint32_t VkMemoryPropertyFlags;
typedef uint32_t RendererCullModeFlagBits;
typedef uint32_t VkCullModeFlagBits;

enum RendererPipelineType;
enum VkPipelineBindPoint;
enum RendererResourceType;
enum VkDescriptorType;
enum RendererImageFormat;
enum VkImageUsageFlags;
enum VkFormat;
enum VkImageLayout;
enum RendererImageLayout;
enum VkAttachmentLoadOp;
enum RendererAttachmentLoadOp;
enum VkAttachmentStoreOp;
enum RendererAttachmentStoreOp;
enum VkShaderStageFlagBits;
enum RendererFrontFace;
enum VkFrontFace;
enum RendererFillMode;
enum VkPolygonMode;
enum RendererPrimitiveTopology;
enum VkPrimitiveTopology;
enum RendererMemoryUsage;
enum VmaMemoryUsage;
struct RendererAttachmentInfo;
struct RV_AllocatedImage;
struct VkExtent3D;
struct VkExtent2D;
struct RendererShaderCreateInfo;
struct VkPipelineShaderStageCreateInfo;

struct VkImageSubresourceRange rv_image_subresource_range(VkImageAspectFlags aspect_mask);
struct VkSemaphoreSubmitInfo rv_create_semaphore_submit_info(VkPipelineStageFlags2 stage_mask, VkSemaphore semaphore);
struct VkCommandBufferSubmitInfo rv_create_command_buffer_submit_info(VkCommandBuffer cmd);
struct VkSubmitInfo2 rv_create_submit_info(struct VkCommandBufferSubmitInfo *cmd, struct VkSemaphoreSubmitInfo *signal_semaphore_info, struct VkSemaphoreSubmitInfo *wait_semaphore_info);

enum VkDescriptorType rv_resource_type_to_vk_descriptor_type(enum RendererResourceType);
VkShaderStageFlags rv_shader_stage_to_vk_shader_stage(RendererShaderStageFlags flags);
enum VkPipelineBindPoint rv_pipeline_type_to_vk_pipeline_bind_point(enum RendererPipelineType pipeline_type);
enum VkImageLayout rv_image_layout_to_vk_image_layout(enum RendererImageLayout image_layout);
enum VkFormat rv_image_format_to_vk_format(enum RendererImageFormat format);
VkImageUsageFlags rv_image_usage_to_vk_image_usage(RendererImageUsageFlags flags);
VkBufferUsageFlags rv_buffer_usage_to_vk_buffer_usage(RendererBufferUsageFlags renderer_flags);
enum VmaMemoryUsage rv_memory_usage_to_vma_memory_usage(enum RendererMemoryUsage renderer_memory_usage);
VkImageAspectFlags rv_vk_format_to_image_aspect(enum VkFormat format);
VkMemoryPropertyFlags rv_image_memory_usage_to_vk_memory_usage(enum RendererMemoryUsage memory_usage);
enum VkImageLayout rv_attachment_type_to_vk_image_layout(RendererAttachmentType attachment_type);
enum VkAttachmentLoadOp rv_attachment_load_op_to_vk_attachment_load_op(enum RendererAttachmentLoadOp renderer_attachment_load_op);
enum VkAttachmentStoreOp rv_attachment_store_op_to_vk_attachment_store_op(enum RendererAttachmentStoreOp renderer_attachment_store_op);
struct VkRenderingAttachmentInfo rv_attachment_info_to_vk_attachment_info(const struct RendererAttachmentInfo *renderer_attachment_info, struct RV_AllocatedImage *image, RendererAttachmentType attachment_type);

struct VkExtent3D rv_renderer_extent_3d_to_vk_extent_3d(const RendererExtent3D *renderer_extent);
RendererExtent3D rv_vk_extent_3d_to_renderer_3d(const struct VkExtent3D *renderer_extent);
struct VkExtent2D rv_renderer_extent_2d_to_vk_extent_2d(const RendererExtent2D *renderer_extent);
RendererExtent2D rv_vk_extent_2d_to_renderer_2d(const struct VkExtent2D *renderer_extent);

int32_t create_pipeline_shader_stage_create_info(struct RendererContext *context, const struct RendererShaderCreateInfo *shader_create_info, enum VkShaderStageFlagBits shader_stage, struct VkPipelineShaderStageCreateInfo *out_pipeline_shader_stage_create_info);

enum VkPrimitiveTopology rv_topology_to_vk_topology(enum RendererPrimitiveTopology topology);
enum VkPolygonMode rv_fill_mode_to_vk_polygon_mode(enum RendererFillMode fill_mode);
VkCullModeFlagBits rv_cull_mode_to_vk_cull_mode(RendererCullModeFlagBits cull_mode);
enum VkFrontFace rv_front_face_to_vk_front_face(enum RendererFrontFace front_face);